#!/bin/bash

_cole_docker_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# ------------------------------------------------------------------------------
# Constants & Variables
# ------------------------------------------------------------------------------

_cole_port=8080
_cole_name='cole-clostra-homework'

_code_volume_source='${_cole_docker_dir}/../code'
_code_volume_target='/srv'

_run_volume_source='${_cole_docker_dir}/../run'
_run_volume_target='/run/cole'


# ------------------------------------------------------------------------------
# Aliases
# ------------------------------------------------------------------------------

echo 'Giving you `doc-init` alias...'
alias doc-init="docker run --rm --name $_cole_name -it \
      -p 8080:8080 \
      -v ${_code_volume_source}:${_code_volume_target} \
      -v ${_run_volume_source}:${_run_volume_target} \
      ${_cole_name}:latest \
      init_server"
echo '  Done.'

echo 'Giving you `doc-cole` alias...'
alias doc-cole="docker run --rm --name $_cole_name -it \
      -p 8080:8080 \
      -v ${_code_volume_source}:${_code_volume_target} \
      -v ${_run_volume_source}:${_run_volume_target} \
      ${_cole_name}:latest \
      run_server"
echo '  Done.'

echo 'Giving you `doc-cmd` alias...'
alias doc-cmd="docker run --rm --name $_cole_name -it \
      -v ${_code_volume_source}:${_code_volume_target} \
      -v ${_run_volume_source}:${_run_volume_target} \
      ${_cole_name}:latest"
echo '  Done.'

echo 'Giving you `doc-build` alias...'
alias doc-build="pushd ${_cole_docker_dir}; ./build.docker.sh; popd"
echo '  Done.'

echo
echo
echo 'How to use is in the README.'
echo
echo 'TL;DR:'
echo '  1. doc-build'
echo '  2. doc-init'
echo '  3. doc-cole'
echo '  4. Run tests in some other terminal.'
