#!/usr/bin/env bash

_test_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "${_test_dir}/_debug.sh"
source "${_test_dir}/_print.sh"


# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

host='localhost' # 127.0.0.1
port=80


# ------------------------------------------------------------------------------
# Functions
# ------------------------------------------------------------------------------

test_title_unnecessarily_pretty() {
    local _title="test"
    local _subtitle='Test `cole` functionality against reqs.'

    max_len "$_subtitle"
    local _width=$LEN_MAX

    if ! build_line $_width '─' ''; then
        echo "version_print: build_line('─') failed?!"
        echo "  build_line $_width '─' '\n'"
        echo "    -> LINE_BUILT: '$LINE_BUILT'"
    fi
    local _solid_line="$LINE_BUILT"

    # ...cuz I'm a sucker for centered titles. >.<
    local _padding=''
    local _left=''
    local _right=''
    (( _padding=($_width - ${#_title}) ))
    (( _left=($_padding / 2) )) # floor
    (( _right=(($_padding + 2 - 1) / 2) )) # ceiling

    dbg_print "width: $_width"
    dbg_print "title: ${#_title}"
    dbg_print "padding: $_padding"
    dbg_print "left: $_left"
    dbg_print "right: $_right"

    # ------------------------------
    # Print out a super-ultra-mega-pretty versions info box.
    # ------------------------------

    printf "    ┌─%s─┐\n" "$_solid_line"
    printf "    │ %${_left}s%s%${_right}s │\n" '' "$_title" ''
    printf "    │ %s │\n" "$_subtitle"
    printf "    └─%s─┘\n" "$_solid_line"

    echo
}


test_run() {
    # Just comment out if not desired:
    test_title_unnecessarily_pretty

    # Run tests.
    /usr/bin/env python3 "${_test_dir}/../code/test/test.py"
}


# ------------------------------------------------------------------------------
# Run
# ------------------------------------------------------------------------------

# Forward all args to test func.
test_run "$@"
